#include <RENDER_ENGINE2.hpp>


void RENDER_ENGINE2::INIT_ENGINE()
{
    VK_INSTANCE.INIT_INSTANCE();
    MAIN_WINDOW.INIT_WINDOW(this->VK_INSTANCE);
    VKP_DEVICE.INIT_DEVICE(this->MAIN_WINDOW, this->VK_INSTANCE);
}

void RENDER_ENGINE2::RUN_ENGINE()
{
    MAIN_WINDOW.WINDOW_LOOP();
}

void RENDER_ENGINE2::FREE_ENGINE()
{
    // MAIN_WINDOW.FREE(VK_INSTANCE);
    VK_INSTANCE.FREE();
}