#include <RENDER_ENGINE2.hpp>


void RENDER_ENGINE2::INIT_ENGINE()
{
    MAIN_WINDOW.INIT_WINDOW();
    VK_INSTANCE.INIT_INSTANCE(MAIN_WINDOW);
}

void RENDER_ENGINE2::RUN_ENGINE()
{
    MAIN_WINDOW.WINDOW_LOOP();
}
