#ifndef VULKAN_SYNC_HPP
#define VULKAN_SYNC_HPP

#include <vulkan/vulkan.h>
#include <VULKAN_LOGICAL_DEVICE.hpp>
#include <VULKAN_SWAPCHAIN.hpp>
#include <VULKAN_SWAPCHAIN.hpp>

#define DEBUG_ON
#include <ETL.hpp>



class VULKAN_SYNC{
    public:
    ETL::DYNAMIC_ARRAY<VkSemaphore> SEMAPHORES_RENDER_FINISHED{1, 1.0f};
    ETL::DYNAMIC_ARRAY<VkSemaphore> SEMAPHORES_IMAGE_AVAILABLE{1, 1.0f};
    ETL::DYNAMIC_ARRAY<SW_CHAIN_IMAGE_AVAILABLE_SEMAPHORES> SEMAPHORES_RENDER_FINISHED_PER_SW{1, 1.0f};
    ETL::DYNAMIC_ARRAY<VkFence> FENCES{1, 1.0f};

    void INIT(VULKAN_LOGICAL_DEVICE& DEVICE, uint8_t FRAMES_IN_FLIGHT, VULKAN_SWAPCHAIN& SW);
    void FREE(VULKAN_LOGICAL_DEVICE& DEVICE);
};

#endif